## spring common config
# mybatis
mybatis:
  type-aliases-package: com.cheney.entity.dto
  mapper-locations: classpath:mybatis/*.xml

## other common config
spring:
  application:
    name: base-project
  # jdbc
  datasource:
    hikari:
      connection-test-query: select 1
      validation-timeout: 3000
      max-lifetime: 30000
      maximum-pool-size: 20
  # jackson
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+08:00
  # mq消息手动确认
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
   # cloud
#  cloud:
#    nacos:
#      discovery:
#        server-addr: ehlxm.nacos.duowan.com:6801
#        namespace: develop

#dubbo:
#  application:
#    id: ${spring.application.name}
#  registry:
#    address: spring-cloud://localhost #采用spring cloud 注册中心
#    address: nacos://localhost:8848 #直接指定nacos
#  scan:
#    base-packages: com.cheney.service
#  cloud: #cloud配置：订阅的服务
#    subscribed-services:

## system config
# jsonWebToken
jwt:
  indate: 30
  sha256:
    key: 182234c3-a3dd-48d5-a107-c628cc80f2df

http:
  util:
   show-log: false

# url
server:
  servlet:
    context-path: ''
# filter url
user:
  auth:
    urlPatterns: ${server.servlet.context-path}/auth/**
  permission:
    ignoreUrls: ${server.servlet.context-path}/auth/safe/**

# ConfigurationProperties示例{@link ExampleProperties}
example:
  properties:
    test: success
