## DB Config
spring:
 datasource:
     url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
     username: root
     password: 2151
     driver-class-name: com.mysql.cj.jdbc.Driver
 profiles:
   active: dev
#mybatis
mybatis:
  typeAliasesPackage: com.cheney.entity.dto
  mapperLocations: classpath:mybatis/*.xml

