##spring config
## DB Config
spring:
 datasource:
     url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
     username: root
     password: 2151
     driver-class-name: com.mysql.cj.jdbc.Driver

## redis
 redis:
  host: 127.0.0.1
  port: 6379
#   password: cheney@redis
  timeout: 100000ms
  jedis:
   pool:
    max-active: 1024
    max-idle: 200
    max-wait: 10000ms
  database: 0

#############################################################

##other config
## redis config
redis:
 throwRedisException: true

## mongodb config
mongodb:
 auth: false
 authBase: admin
 host: 127.0.0.1
 port:
 database: blog
 username: root
 password: cheney@mongo

#rabbitmq
rabbitmq:
 host: localhost
 username: guest
 password: guest
