##spring common config
#mybatis
mybatis:
  typeAliasesPackage: com.cheney.entity.dto
  mapperLocations: classpath:mybatis/*.xml

#############################################################

##other common config
## Freemarker Template Config
template:
  number_format: 0.\#\#\#\#\#\#
  datetime_format: yyyy-MM-dd
  time_format: HH\:mm\:ss
  boolean_format: true,false
  update_delay: 0
  encoding: UTF-8
  date_format: yyyy-MM-dd
  loader_path: /WEB-INF/template
  tag_syntax: auto_detect

#java mail
mail:
  smtp:
    auth: true
    timeout: 25000
  ssl:
    enable: true
  socketFactory:
    class: javax.net.ssl.SSLSocketFactory
