## spring common config
# mybatis
mybatis:
  type-aliases-package: com.cheney.entity.dto
  mapper-locations: classpath:mybatis/*.xml

## other common config
spring:
  application:
    name: base-project
  # jdbc
  datasource:
    hikari:
      connection-test-query: select 1
      validation-timeout: 3000
      max-lifetime: 30000
      maximum-pool-size: 20
     # druid
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initialSize: 50
#      maxActive: 100
#      maxWait: 5000
#      minEvictableIdleTimeMillis: 300000
#      minIdle: 50
#      name: ${spring.application.name}
#      testOnBorrow: false
#      testOnReturn: false
#      testWhileIdle: true
#      timeBetweenEvictionRunsMillis: 60000
#      validConnectionCheckerClassName: com.alibaba.druid.pool.vendor.MySqlValidConnectionChecker
#      validationQuery: select 1
#      validationQueryTimeout: 2
#      filter:
#        stat:
#          enabled: true
#          log-slow-sql: true
#          slow-sql-millis: 1000
  # jackson
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+08:00
  # mq消息手动确认
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
   # cloud
#  cloud:
#    nacos:
#      discovery:
#        enabled: true
#        server-addr: ehlxm.nacos.duowan.com:6801
#        namespace: develop

#dubbo:
#  application:
#    id: ${spring.application.name}
#  registry:
#    address: spring-cloud://localhost #采用spring cloud 注册中心（2021.1版本待验证）
#    address: nacos://localhost:8848 #直接指定nacos
#  scan:
#    base-packages: com.cheney.service
#  cloud: #cloud配置：订阅的服务
#    subscribed-services:

## system config
# jsonWebToken
jwt:
  indate: 30
  sha256:
    key: 182234c3-a3dd-48d5-a107-c628cc80f2df

http:
  util:
   show-log: false

# url
server:
  servlet:
    context-path: ''
# filter url
user:
  auth:
    urlPatterns: ${server.servlet.context-path}/auth/**
  permission:
    ignoreUrls: ${server.servlet.context-path}/auth/safe/**

# ConfigurationProperties示例{@link ExampleProperties}
example:
  properties:
    test: success
