##spring common config
#mybatis
mybatis:
  type-aliases-package: com.cheney.entity.dto
  mapper-locations: classpath:mybatis/*.xml

##other common config

#jsonWebToken
jwt:
  indate: 30
  sha256:
    key: 182234c3-a3dd-48d5-a107-c628cc80f2df

#filter url
user:
  auth:
    urlPatterns: /auth/*
  permission:
    ignoreUrls: /auth/logout

#java mail
mail:
  smtp:
    auth: true
    timeout: 25000
  ssl:
    enable: true
  socketFactory:
    class: javax.net.ssl.SSLSocketFactory

spring:
  # jdbc
  datasource:
    hikari:
      connection-test-query: select 1
      validation-timeout: 3000
      max-lifetime: 30000
  # jackson
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+08:00
  # mq消息手动确认
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual

# ConfigurationProperties示例{@link ExampleProperties}
example:
  properties:
    test: success
