##spring config
## DB Config
spring:
 datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: cheney@mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
 data:
  mongodb:
   uri: mongodb://localhost:27017/test
 ## kafka
 kafka:
  bootstrap-servers: '192.168.99.100:9092'
  producer:
   acks: 1
   key-serializer: org.apache.kafka.common.serialization.StringSerializer
   value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
   auto-offset-reset: earliest
   enable-auto-commit: false
   group-id: test
   value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  listener:
   ## 手动确认消费
   ack-mode: manual
   ## 开启批量消费
   type: batch
   ## 监听实例数（默认1，由于kafka客户端实例应<=分区数：机器数量*concurrency <= 分区数）
   concurrency: 3
 elasticsearch:
  rest:
   uris: 127.0.0.1:2910

 ## redis
 redis:
  host: 127.0.0.1
  port: 6379
#  cluster:
#   nodes:
#   - 127.0.0.1:6379
#   - xxx.x.x.x:xxxx
#  password: cheney@redis
  timeout: 30000ms
  database: 0
#  jedis:
#   pool:
#    max-active: 16
#    max-idle: 16
#    max-wait: 30000ms
  lettuce:
   pool:
    max-active: 16
    max-idle: 16
    max-wait: 10000ms
   cluster:
    refresh:
     adaptive: true
     period: 3000

 #rabbitmq
 rabbitmq:
  host:

#############################################################

##other config
## redis config
redis:
 throwRedisException: true

toolbox:
 entity-cache:
  enable: true
  type: REDIS
  underline: true
  entityPaths: com.cheney.entity
  autoRefresh: true
  period: 1

