##spring common config
#mybatis
mybatis:
  type-aliases-package: com.cheney.entity.dto
  mapper-locations: classpath:mybatis/*.xml

##other common config

#jsonWebToken
jwt:
  indate: 30
  sha256:
    key: 182234c3-a3dd-48d5-a107-c628cc80f2df

#filter url
user:
  auth:
    urlPatterns: /user/*

#java mail
mail:
  smtp:
    auth: true
    timeout: 25000
  ssl:
    enable: true
  socketFactory:
    class: javax.net.ssl.SSLSocketFactory

#mq消息手动确认
spring:
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual